### ISSUE TITLE
Link directly to naked-singularity repo

### ISSUE THREAD

**Issue by mkandes** [zonca/expanse_singularity#12]
@zonca - I think this would be more useful to the reader. Otherwise, its then difficult for them to make the leap following your logic right thereafter when you refer to the directory structure of the repo itself. You can find an example of linking to another repo in github markdown. You can find an example of how to do this in the introductory section of my README.md for galyleo, where I point back to the Satellite repo maintained by @scottsaki and @marypthomas 

[naked-singularity](https://github.com/mkandes/galyleo

**Comment by mkandes** [comment]
P.S. Let me know if you want me to submit some pull request(s). I can help out if you don't have time and are working on other issues.

**Comment by zonca** [comment]
I don't understand what you are referring to.
It would be easier if you used the Github review interface, so you can point to the file and to the line you are talking about:
https://github.com/zonca/expanse_singularity/pull/6/files
