### ISSUE TITLE
Give prominence to prebuilt containers

### ISSUE THREAD

**Issue by zonca** [zonca/expanse_singularity#5]
@shm7 I asked Marty Kandes for feedback he informed me that most people actually use prebuilt containers,
so it is ok if I heavily restructure the tutorial, put prebuilt containers and how to run them first,
and then only later explain how to modify/build from scratch?

**Comment by shm7** [comment]
Yes, that sounds like a good plan.

**Comment by shm7** [comment]
Absolutely fine!

From: Andrea Zonca ***@***.***>
Date: Tuesday, May 10, 2022 at 6:31 PM
To: zonca/expanse_singularity ***@***.***>
Cc: Susan H. Mehringer ***@***.***>, Mention ***@***.***>
Subject: [zonca/expanse_singularity] Give prominence to prebuilt containers (Issue #5)

@shm7<https://github.com/shm7> I asked Marty Kandes for feedback he informed me that most people actually use prebuilt containers,
so it is ok if I heavily restructure the tutorial, put prebuilt containers and how to run them first,
and then only later explain how to modify/build from scratch?
